CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=1
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

CONFIG_ZMK_SLEEP=n
# CONFIG_PM_DEVICE=n
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
CONFIG_ZMK_EXT_POWER=y
# CONFIG_USB_DEVICE_VID	int	The vendor ID advertised to USB	0x1D50
# CONFIG_USB_DEVICE_PID	int	The product ID advertised to USB	0x615E
CONFIG_USB_DEVICE_VID=0x1D50
CONFIG_USB_DEVICE_PID=0x615A
CONFIG_USB_DEVICE_SN="2123456789ABCDEF"
CONFIG_USB_DEVICE_PRODUCT="nice!60"
CONFIG_ZMK_USB=y
CONFIG_ZMK_USB_HID_INIT_PRIORITY=41
CONFIG_ZMK_USB_INIT_PRIORITY=40